# OpenVPN Server Configuration for Hybrid PQC Integration
port 1194
proto udp
dev tun
topology subnet
server 10.8.0.0 255.255.255.0

# Management Socket Interface
management 127.0.0.1 7505

cipher AES-256-GCM
keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
verb 3
